develop branch
pinggubanggu/board pull request #1
Opened 2021-12-01 06:33 UTC by pinggubanggu

develop branch 만듬

2021-12-01 08:34 UTC, kimyouilm commented on build.gradle
> +plugins {
영운님 dev branch는 master에서 빼신거 아닌가요? 
commit 내용이 "develop branch 만듬"인데

push 하시는 파일들이 gradle 설정및 초기 설정이네요.

master -> develop -> dev_기능  순으로 하신다음에
dev_기능에서 dev로 push후 전체 테스트 한 다음에  master에 push 하는 순서로 request날리신게 맞는지 확인 부탁드립니다.

1. 순서가 어떻게 되는건가요.
2. 초기 설정을 dev에서 하신건가요?

2021-12-01 08:35 UTC, kimyouilm requested changes
comment 확인해주시고 톡주세요!

2021-12-01 15:11 UTC, pinggubanggu commented on build.gradle
> +plugins {
제가 하고 있는 방법이 리마님이 말씀하신 것이 맞는지 모르겠습니다. 제가 했던 것을 정리해서 말씀드리겠습니다.

1. git init
2. 현재 branch는 없음.
3. git remote origin http주소 -> 기본 master 브랜치 생김
4. git branch develop 만듬 
5. git checkout develop
6. git push origin develop -> 했으나, Everything up-to-date라고 develop branch가 push가 안되서 설정 및 초기파일 추가
7. git add . -> git commit -> git push origin develop 하여 develop branch push -> remote에 반영
8. github에서 pull request를 master <- develop로 함
9. git branch dev-sql-mybatisMapper 만듬 -> git checkout dev-sql-mybatisMapper
10. sql, mybatisMapper 기능 만들고 , 다시 7번처럼 add -> commit -> git push origin dev-sql-mybatisMapper
      -> remote 반영
11. git hub에서 pull request를 develop <- dev-sql-mybatisMapper로 함

지금 한 것이 올바른 방법과 순서로 한 것인지 commet 부탁 드립니다.
제가 git 개념 부분이 많이 부족한 것 같아서 내일부터 git youtube 강의를 찾아서 보도록 하겠습니다.

2021-12-01 15:45 UTC, kimyouilm commented on build.gradle
> +plugins {
git init
현재 branch는 없음.
git remote origin http주소 -> 기본 master 브랜치 생김
---------------------------------------------------------------여기까지 오케이

master에서 기본 개발 환경을 구성 -------dev branch 생성 -------->  master에서 개발환경 구성해놓은 dev로 개발 시작 입니다!

dev에서 개발환경을 구성하는것이 아닙니다!
어어엄청 중요한건 아니니까 그렇구나 정도로만 알고있으시면됩니다!
회사마다 차이는 있겠지만 보통은 이렇게 한다 정도만 알고계세여!

2021-12-02 03:43 UTC, pinggubanggu commented on build.gradle
> +plugins {
리마님 피드백 + 공부하고 다시 만들어본 Git 방식		
 
1. 개발환경 만듬 -> git init -> git remote origin http:주소 -> master 브랜치 자동 생성
2. git branch develop -> git checkout develop 
3. git push –set-upstream origin develop  -> GitHub by visiting  master <- develop로 create pull request
4. git branch dev-function -> git checkout dev-function ->기능 작업 수행, and 완료
   질문 : develop branch에서 기능-branch(dev-function)를 따는게 이렇게 하는게 맞나요?

5. git add . -> git commit -> local repository dev-function에 저장 완료
6. git push origin dev-function -> GitHub by visiting  develop <- dev-function로 create pull request
7. git checkout develop -> git merge dev-function
8. git branch dev-function2 
  질문 : 다시 develop branch로 가서 기능-branch2를 따서 작업하는 게 맞을까요?
9.  3번 ~7번 실행

그 외 질문 : develop -> master로 push 할 때는 github에서 하는게 아니라 
                   local에서 merge develop해서 master를 remote에 push하는 건가요?

2021-12-02 11:39 UTC, kimyouilm commented on build.gradle
> +plugins {
4. 질문 : develop branch에서 기능-branch(dev-function)를 따는게 이렇게 하는게 맞나요?
=> 네 맞아요 master에서 개발에 필요한 설정을 끝내고 --> dev branch 생성 --> dev-기능 branch 생성
      잘하셨습니다!

6. git push origin dev-function -> GitHub by visiting develop <- dev-function로 create pull request
=> dev-function로 create pull reques 이게 dev-function 에서 develop 로 저한테 pull request 날리시는거죠?

7. git checkout develop -> git merge dev-function
=> 이 행위 부분이 request에서 제가 merge하시면될꺼같습니다. 한 다음에 하시는 행위가 맞을까요?
      pull request 날리시면 따로 "git checkout dev" 하고 "git merge dev-~" 안하셔도 merge 버튼으로 merge 됩니다.
     
8. develop branch 테스트 후 괜찮음 -> git push origin develop
    -> GitHub by visiting master <- develop로 create pull request
    질문 : 기능1, 기능2, 기능 3 등... 을 만들어 최종으로 다 만들고, 테스트 다 마치고 master에 push하나요?
    아니면 기능1 만들고 8번처럼 하나요?
=> case by case 이긴합니다만 보통 
     기능이 얼추 만들어지고 유닛테스트 통합테스트 전부 통과하면 master에 push하긴합니다!
      그전까지는 dev에 계속 push 하다가요

9. git branch dev-function2
   질문 : 다시 develop branch로 가서 기능-branch2를 따서 작업하는 게 맞을까요?
=> 저한테 dev로 push 하는 pull request 날리시는 중간에 branch를 따시는 거면
      현재 진행중이였던 dev-기능에서 따시는게 맞습니다. (이부분 해깔리면 시간될때 직접 말씀드릴께요.)

11. develop -> master로 push 할 때는 github에서 하는게 아니라
local에서 merge develop해서 master를 remote에 push하는 건가요?
=> 이부분은 이해가 안됩니다. github로 하는게 아니라 local에서 한다는 의미를 모르겠습니다.
      git 으로 pull request 안날리고 그냥 명령어로 merge하신다는 의미일까요?

2021-12-02 12:53 UTC, pinggubanggu commented on build.gradle
> +plugins {
4. git push origin dev-function -> GitHub by visiting develop <- dev-function로 create pull request
   => dev-function로 create pull reques 이게 dev-function 에서 develop 로 저한테 pull request 날리시는거죠? 
   --> 네!

5. git checkout develop -> git merge dev-function
  => 이 행위 부분이 request에서 제가 merge하시면될꺼같습니다. 한 다음에 하시는 행위가 맞을까요?
  pull request 날리시면 따로 "git checkout dev" 하고 "git merge dev-~" 안하셔도 merge 버튼으로 merge 됩니다.
  --> 5번의 의미는 local develop 에서 dev-function을 merge 한다는 의미 였습니다. 
      github(remote)에서 리마님 말씀대로 pull request 날리면 따로 "git checkout dev" 하고 "git merge dev-~" 안하셔도 
       merge 버튼으로 local repo(branch)도 merge가 되는건가요?

2021-12-02 13:15 UTC, kimyouilm commented on build.gradle
> +plugins {
일요일날 말씀드리겠습니다! 이부분  issue로 남겨주세요.
이 comment는 resolve하겠습니다.

2021-12-02 13:15 UTC, kimyouilm commented
수고하셨습니다.

2021-12-02 13:15 UTC, kimyouilm approved these changes

2021-12-02 13:27 UTC, merged