add sql, mybatisMapper
pinggubanggu/board pull request #2
Opened 2021-12-01 06:34 UTC by pinggubanggu

develop branch 아래에 dev-sql-mybatisMapper branch 만들어서 기능 추가

2021-12-01 08:47 UTC, kimyouilm commented on src/main/resources/mappers/BoardMapper.xml
> +<?xml version="1.0" encoding="UTF-8"?>
xml 정렬..... 부탁드려여..... .     **┗|｀O′|┛**

2021-12-01 08:47 UTC, kimyouilm commented on src/test/java/com/board/MapperTests.java
> +
혹시 google style 쓰시고있는지 확인 부탁드립니다~

2021-12-01 15:15 UTC, pinggubanggu commented on src/main/resources/mappers/BoardMapper.xml
> +<?xml version="1.0" encoding="UTF-8"?>
리마님, mybatis xml mapper 형식으로 만들 때 자동으로 만들어진 형식입니다. 
찾아보니 이런 형식인 것 같은데 혹시 어떤 부분을 정렬을 해야 하는지 알려주시면 감사하겠습니다.

2021-12-01 15:30 UTC, pinggubanggu commented on src/test/java/com/board/MapperTests.java
> +
안 쓰고 있었습니다. 바로 xml 파일 다운 받아서 IDE에 적용하였습니다. 감사합니다.

2021-12-01 15:46 UTC, kimyouilm commented on src/test/java/com/board/MapperTests.java
> +
issue 생성해주시고 다음 request 때 언급해주세요
이 comment는 resolve 하겠읍니다.

2021-12-01 16:42 UTC, kimyouilm requested changes

2021-12-01 17:08 UTC, kimyouilm requested changes

2021-12-01 17:08 UTC, lima1016 commented on src/main/java/com/board/configuration/DBConfiguration.java
>  public class DBConfiguration {
class에 선언하신 method를 보니 DB설정은 아니고 Mybatis 설정인거 같은데 MybatisConfig  같이 Mybatis 관련으로 이름을 바꾸시게 좋을 것 같습니다.

2021-12-01 17:11 UTC, kimyouilm commented on src/main/resources/mappers/BoardMapper.xml
> +<?xml version="1.0" encoding="UTF-8"?>
![image](https://user-images.githubusercontent.com/17001517/144280898-069c7d53-f309-4d6c-9e70-1924664e4fa5.png)

sql 가독성 부분에서 tab이냐 space bar 이냐의 차이가 좀 있습니다! 참고해서 가독성을 높여주세여!
이부분 수정하셔서 다시 push 해주세요!

2021-12-02 00:38 UTC, pinggubanggu commented on src/main/resources/mappers/BoardMapper.xml
> +<?xml version="1.0" encoding="UTF-8"?>
네! 리마님이 첨부해주신 이미지 보고 이해하기가 쉬웠습니다. 참고하여 수정하였습니다.

2021-12-02 00:42 UTC, pinggubanggu commented on src/main/java/com/board/configuration/DBConfiguration.java
>  public class DBConfiguration {
네! 클래스 이름 DBConfiguration -> MybatisConfiguration로 변경하였습니다.

2021-12-02 11:41 UTC, kimyouilm commented on src/main/java/com/board/configuration/DBConfiguration.java
>  public class DBConfiguration {
변경 후 comment다실때 변경된 부분 링크 걸어주세요!
일단 commit 하신거 확인했습니다! 이 comment는 resolve하겠습니다!

2021-12-02 11:41 UTC, kimyouilm approved these changes

2021-12-02 11:42 UTC, kimyouilm commented
확인했습니다.
수고하셨습니다.

2021-12-02 12:51 UTC, merged