bootstrap설정, Boardservice, Boardcontroller 만듬
pinggubanggu/board pull request #5
Opened 2021-12-06 13:24 UTC by pinggubanggu

2021-12-07 04:28 UTC, kimyouilm requested changes

2021-12-07 04:28 UTC, kimyouilm commented on src/main/java/com/board/controller/BoardController.java
> +  @GetMapping(value = "/board/write.do")
질문!
write.do 가 write.html 혹은 write.jsp 같은걸까요?

2021-12-07 04:28 UTC, kimyouilm commented on src/main/java/com/board/controller/BoardController.java
> +    return "board/write";
`return "redirect:/board/list.do";`
27번 라인에서는 redirect 하고 .do 로 return을 주셨는데
여기는 board/write만 해도 redirect가 되는건지 궁금하고 .do 가 아니어도 괜찮은지 궁금합니다.

2021-12-07 04:28 UTC, kimyouilm commented on src/main/java/com/board/service/BoardServiceImpl.java
> +package com.board.service;
google style적용 안되신거같습니다!
그리고 정렬이 제대로 안됐습니다!

2021-12-07 04:44 UTC, pinggubanggu commented on src/main/java/com/board/controller/BoardController.java
> +  @GetMapping(value = "/board/write.do")
write.html 입니다.

2021-12-07 04:55 UTC, kimyouilm commented on src/main/java/com/board/controller/BoardController.java
> +  @GetMapping(value = "/board/write.do")
넵 알려주셔서 감사합니다.

2021-12-07 04:58 UTC, pinggubanggu commented on src/main/java/com/board/service/BoardServiceImpl.java
> +package com.board.service;
확인해보았는데, google style 적용 되었습니다. service는 google style 적용하기 전에 코드작성하였습니다.

2021-12-07 05:20 UTC, kimyouilm commented on src/main/java/com/board/service/BoardServiceImpl.java
> +package com.board.service;
style 적용 후 재정렬 하셔야합니다.

2021-12-08 12:22 UTC, kimyouilm approved these changes

2021-12-08 12:26 UTC, pinggubanggu commented on src/main/java/com/board/controller/BoardController.java
> +    return "board/write";
url 확장자로써의 .do의 의미는 아니고, 전에 썼던 관행으로 쓰신 것 같습니다.
.do의 의미를 몰라서 찾아보았습니다. 참고자료는 아래에 링크 걸어 놓았습니다. 
참고 자료 : https://okky.kr/article/262795

2021-12-08 12:26 UTC, pinggubanggu commented on src/main/java/com/board/service/BoardServiceImpl.java
> +package com.board.service;
네! 재정렬 후 dev-sql-mybatis branch로 수정사항 push 하였습니다. 
https://github.com/pinggubanggu/board/pull/6/commits/b0628b4df9960a0b6cba7647d82e96f2c74895c7

2021-12-08 12:27 UTC, kimyouilm commented on src/main/java/com/board/controller/BoardController.java
> +    return "board/write";
네 확인했습니다 resolve하겠습니다.

2021-12-08 12:28 UTC, kimyouilm commented on src/main/java/com/board/service/BoardServiceImpl.java
> +package com.board.service;
확인했습니다 resolve하겠습니다.

2021-12-08 12:28 UTC, kimyouilm approved these changes

2021-12-08 12:45 UTC, merged